### PR TITLE
Adding Jayco Terrain Support

### PR DESCRIPTION
**Pull request by mkostersitz**

### CODE REVIEW

**Comment by oilcan-productions** [comment]
Added support for Jayco Terrain and Entegra Launch with the G12 system.
Tested and verified working on my 2023 Jayco Terrain 19Y.
Also tried it at a Dealership with a 2023 Entegra Launch
Added an eventhandler for HomeSpan StatusUpdate to see when HomeSpan is ready in the serial output. It helped me with troubleshooting WiFi issues
@rubillos can you take a look if this is OK?

**Review by rubillos — CHANGES_REQUESTED** [review]
Your code changes look fine, the only issues are:
- You've removed config-sample.h, I think you moved and renamed it rather than duplicating it.
- It would be better to name your definition file 'Jayco_2023_Terrain.h' to match the the existing files.
Thanks!

**Comment by oilcan-productions** [comment]
@rubillos I made the suggested changes and added the sample back.

Thanks!

**Comment by rubillos** [comment]
Awesome, thanks!

**Pull request merged**
